# Generated by Django 5.0.7 on 2024-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.CharField(max_length=30),
        ),
    ]
